import qrcode
import streamlit as st

st.header('generate QRCode')
st.subheader('This is the python code generated by ChatGPT')
st.text('QRコードを生成する文字列をテキストボックスに入力してください')
st.text('Enter a string to generate a QR code in the textbox.')

title = st.text_input('Enter a string', 'example http://hexadec.blog/')
st.write('The current title is', title)


# QRコードに変換する文字列
data = title
qr = qrcode.QRCode(version=1, box_size=10, border=5)

# QRコードを生成する
img = qrcode.make(data)

# 生成したQRコードをファイルに保存する
img.save("example.png")

with open("example.png", "rb") as file:
    btn = st.download_button(
            label="Download QR code",
            data=file,
            file_name="generated qrcode.png",
            mime="image/png"
          )

st.write('コードが必要な方は下記よりダウンロード又はForkしてご利用下さい')
st.write('https://github.com/norihisayamada/generate-QRCode')